### ISSUE TITLE
Question on applications of this

### ISSUE THREAD

**Issue by BenjyP1235** [JJTech0130/MultiMC-Patcher#7]
I have an ARM CPU on my Surface pro X running Windows 10. Constantly have the issue of being unable to use software that only runs on 64bit as they do not support ARM, minecraft is included in this. Have found this which works in some similar capacity on linux, can it be applied to MultiMC on Windows 10 ARM.

**Comment by JJTech0130** [comment]
This patcher is not designed for windows. https://github.com/JJTech0130/MultiMC5/issues/34 got started on support for the native arm version of MMC, however there is no OpenGL support so it would take some work

**Comment by JJTech0130** [comment]
Closing as the patcher won't get adapted, *maybe* the native version will.
